name: markdown_docs_flutter
description: Creates flutter widgets from markdown text.
version: 1.0.0-dev.3
homepage: https://adrianos42.github.io/markdown_docs_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop: ^5.0.0-dev.3
  markdown_docs: any
  url_launcher: ^6.0.3
  path: ^1.8.2
  # desktop:
  #   path: ../../desktop/desktop
  # markdown_docs:
  #   path: ../../markdown_docs
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1