name: markdown_docs_flutter
description: Creates flutter widgets from markdown text.
version: 1.0.0-dev.2
homepage: https://adrianos42.github.io/markdown_docs_flutter

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  desktop: ^4.0.0-dev.6
  markdown_docs: ^1.0.0-dev.3
  url_launcher: ^6.0.3
  path: ^1.8.2

dependency_overrides:
  desktop:
    path: ../../desktop/desktop
  markdown_docs:
    path: ../../markdown_docs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1